name: build and test project 

on:
  push:
    branches: 
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: chckout the repos
      uses: actions/checkout@v4
    - name: list all directory
      run: ls -la
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'    
    
    - name: Check Maven version
      run: mvn --version
    
    - name: run maven
      run: mvn -B clean package -DskipTests
    
    - name: test with maven
      run: mvn test
      
